#ifndef _DB_character_detail_2_
#define _DB_character_detail_2_

enum DB_character_detail_2
{
	DB_character_detail_2_object_id = 0,
	DB_character_detail_2_temp1,
	DB_character_detail_2_temp2,
	DB_character_detail_2_temp3,
	DB_character_detail_2_temp4,
	DB_character_detail_2_temp5,
	DB_character_detail_2_temp6,
	DB_character_detail_2_temp7,
	DB_character_detail_2_temp8,
	DB_character_detail_2_temp9,
	DB_character_detail_2_temp10,
	DB_character_detail_2_temp11,
	DB_character_detail_2_temp12,
	DB_character_detail_2_temp13,
	DB_character_detail_2_temp14,
	DB_character_detail_2_temp15,
	DB_character_detail_2_temp16,
	DB_character_detail_2_temp17,
	DB_character_detail_2_temp18,
	DB_character_detail_2_temp19,
	DB_character_detail_2_temp20,
	DB_character_detail_2_temp21,
	DB_character_detail_2_temp22,
	DB_character_detail_2_temp23,
	DB_character_detail_2_temp24,
	DB_character_detail_2_temp25,
	DB_character_detail_2_temp26,
	DB_character_detail_2_temp27,
	DB_character_detail_2_temp28,
	DB_character_detail_2_temp29,
	DB_character_detail_2_temp30,
	DB_character_detail_2_temp31,
	DB_character_detail_2_temp32,
	DB_character_detail_2_temp33,
	DB_character_detail_2_temp34,
	DB_character_detail_2_temp35,
	DB_character_detail_2_temp36,
	DB_character_detail_2_temp37,
	DB_character_detail_2_temp38,
	DB_character_detail_2_temp39,
	DB_character_detail_2_temp40,
	DB_character_detail_2_temp41,
	DB_character_detail_2_temp42,
	DB_character_detail_2_temp43,
	DB_character_detail_2_temp44,
	DB_character_detail_2_temp45,
	DB_character_detail_2_temp46,
	DB_character_detail_2_temp47,
	DB_character_detail_2_temp48,
	DB_character_detail_2_temp49,
	DB_character_detail_2_temp50,
	DB_character_detail_2_temp51,
	DB_character_detail_2_temp52,
	DB_character_detail_2_temp53,
	DB_character_detail_2_temp54,
	DB_character_detail_2_temp55,
	DB_character_detail_2_temp56,
	DB_character_detail_2_temp57,
	DB_character_detail_2_temp58,
	DB_character_detail_2_temp59,
	DB_character_detail_2_temp60,
	DB_character_detail_2_temp61,
	DB_character_detail_2_temp62,
	DB_character_detail_2_temp63,
	DB_character_detail_2_temp64,
	DB_character_detail_2_MAXI
};

#endif // _DB_character_detail_2_
