enum EMOTE_TYPE
{
	EMOTE_TYPE_INSPECTION = 1, //1
	EMOTE_TYPE_FAST_INSPECTION, //2
	EMOTE_TYPE_NONE3, //3
	EMOTE_TYPE_NULL4, //4
	EMOTE_TYPE_NONE5, //5
	EMOTE_TYPE_NULL6, //6
	EMOTE_TYPE_NULL7, //7
	EMOTE_TYPE_NULL8,//8
	EMOTE_TYPE_NULL9, //9
	EMOTE_TYPE_NULL10, //10
	EMOTE_TYPE_CHEMISTRY, //11
	EMOTE_TYPE_SMITH, //12
	EMOTE_TYPE_SEWS,//13
	EMOTE_TYPE_BOW,//14	
	EMOTE_TYPE_NULL15, //15
	EMOTE_TYPE_HELLO, //16
	EMOTE_TYPE_BUW, //17
	EMOTE_TYPE_LAUGHTER, //18
	EMOTE_TYPE_CRYING, //19
	EMOTE_TYPE_BOASTING, //20
	EMOTE_TYPE_DANCE, //21
	EMOTE_TYPE_DULL, //22
	EMOTE_TYPE_SLAM, //23
	EMOTE_TYPE_I_LOVE_YOU, //24
	EMOTE_TYPE_MUSE, //25
	EMOTE_TYPE_HEART, //26
	EMOTE_TYPE_SHOW_ON_TERGET,//27
	EMOTE_TYPE_POINT_FINGER,//28
	EMOTE_TYPE_DISORDER,//29
	EMOTE_TYPE_FAIL,//30
	EMOTE_TYPE_INSPECT,//31
	EMOTE_TYPE_KNEAD_FISTS,//32
	EMOTE_TYPE_BUMPING, //33
	EMOTE_TYPE_TALK, //34
	EMOTE_TYPE_EXPLANATION, //35
	EMOTE_TYPE_EXPLANATION_2, //36
	EMOTE_TYPE_CAST, //37
	EMOTE_TYPE_SIT_DOWN, //38
	EMOTE_TYPE_STAND_UP, //39
	EMOTE_TYPE_MOUNT_LOOKING, //40
	EMOTE_TYPE_MOUNT_YAWN, //41
	EMOTE_TYPE_MOUNT_TALK, //42
	EMOTE_TYPE_HELLO2, //43
	EMOTE_TYPE_DANCE2, //44
	EMOTE_TYPE_SIT_DOWN2, //45
	EMOTE_TYPE_TAKE_POS, //46
	EMOTE_TYPE_NONE18, //47
	EMOTE_TYPE_NONE19, //48
	EMOTE_TYPE_NONE20, //49
	EMOTE_TYPE_NONE21, //50
	EMOTE_TYPE_NONE22, //51
	EMOTE_TYPE_NONE23 //52
};
