
enum SlotType {
	SLOT_WEAPON = 0, // 0
	SLOT_EMPTY_1,
	SLOT_ARMOR,	 // 2
	SLOT_GLOVES,	 // 3
	SLOT_BOOTS,	 // 4
	SLOT_EARRING_L,	 // 5
	SLOT_EARRING_R,	 // 6
	SLOT_RING_L,	 // 7
	SLOT_RING_R,	 // 8
	SLOT_NECKLACE,	 // 9
	SLOT_SHIRT,	 // 10
	SLOT_HAT,	 // 11
	SLOT_MASK,	 // 12
	SLOT_APP_HAT,	 // 13
	SLOT_APP_MASK,	 // 14
	SLOT_APP_WEAPON, // 15
	SLOT_APP_ARMOR,	 // 16
	SLOT_APP_BACK,	 // 17
	SLOT_BELT,	 // 18
	SLOT_BROOCH	 // 19
};
